name: BlockPalletGUI
version: '1.1'
main: org.example.bte.blockPalletGUI.Main
api-version: '1.20'
commands:
  blockpallet:
    description: Opens the block pallet menu.
    usage: /blockpallet [filter|menu|filter <filter1> <filter2> ...]
    aliases: [bp, blocks]
    permission: blockpallet.use

permissions:
  blockpallet.use:
    description: Allows players to use /blockpallet
    default: true
